### ISSUE TITLE
Cannot go back from sponsors page

### ISSUE THREAD

**Issue by shrtminded** [72Fest/72FestHybridApp#40]
On the sponsors tab if you click on a sponsor it takes you to the sponsors website.  However there is no way to go back to see all the sponsors.  If you click on the sponsors link from the menu it takes you back to whatever sponsor website you last clicked

**Comment by LonnyGomes** [comment]
@howell13 and I agreed that it's best to move the sponsors to the database and render the page within the app. It currently is "cheating" by using an iframe.

**Comment by LonnyGomes** [comment]
Note that there is a related server-side issue [here](https://github.com/72Fest/72FestWebApp/issues/25).
